version: "3"
services:
    node-app:
        build: .
        ports: 
            - "3000:3000"
        volumes: 
            - ./:/app
        environment: 
            - PORT=3000
        # env-file:
        #     - ./.env
